In [2]:
import numpy as np

In [3]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [4]:
a = np.array([1,2,3,4,5,6])

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
print(a[0])

[1 2 3 4]


In [7]:
a[0]

array([1, 2, 3, 4])

In [8]:
a = np.array([1,2,3])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.empty(2)

array([1., 1.])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# 요소 추가, 제거 및 정렬

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

- argsort
- lexsort
- serarchsorted
- partition

In [18]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [19]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [21]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
x

array([[1, 2],
       [3, 4]])

In [23]:
y

array([[5, 6]])

In [24]:
(np.concatenate((x,y), axis=0)).shape

(3, 2)

# 배열의 모양과 크기
- ndarray.ndim : 배열의 축 또는 차원 수
- ndarray.size :  배열의 총 요소 수(=배열 모양 요소의 곱)
- ndarray.shape : 배열의 각 차원을 따라 저장된 요소 수를 나타내는 정수 튜플

In [25]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [26]:
# 배열의 차원 수
array_example.ndim

3

In [27]:
# 배열의 총 요소 수
array_example.size

24

In [28]:
# 배열의 모양
array_example.shape

(3, 2, 4)

# 배열 재구성

In [29]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [31]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

order 이거 잘 모르겠다 뭔 말이지

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

# 1D -> 2D

In [32]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [33]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [34]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [35]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [36]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [37]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [38]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# 인덱싱 및 슬라이싱

In [39]:
data = np.array([1,2,3])

data[1]

2

In [40]:
data[0:2]

array([1, 2])

In [41]:
data[1:]

array([2, 3])

In [42]:
data[-2:]

array([2, 3])

In [43]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [44]:
print(a[a < 5])

[1 2 3 4]


In [45]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [46]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [47]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [48]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [49]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [50]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [51]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [52]:
list(zip(b[0], b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [53]:
print(a[b])

[1 2 3 4]


In [54]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# 기존 데이터에서 배열 만들기

In [55]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [56]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [57]:
a1 = np.array([[1,1],
              [2,2]])
a2 = np.array([[3,3],
              [4,4]])

In [58]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [59]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [60]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [62]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

## 슬라이싱(얕은 복사)과 copy(깊은 복사)

In [63]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [64]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [65]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [66]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
b2 = a.copy()

In [68]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
b2[0, 0] = 1

In [70]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 기본 배열 작업

In [72]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [73]:
data - ones

array([0, 1])

In [74]:
data * data

array([1, 4])

In [75]:
data / data

array([1., 1.])

In [76]:
a = np.array([1,2,3,4])
a.sum()

10

In [77]:
b = np.array([[1,1], [2,2]])

In [78]:
b.sum(axis=0)

array([3, 3])

In [79]:
b

array([[1, 1],
       [2, 2]])

In [80]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

In [81]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

# More useful array operations

In [82]:
data.max()

2.0

In [83]:
data.min()

1.0

In [84]:
data.sum()

3.0

In [85]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [86]:
a.sum()

4.8595784

In [87]:
a.min()

0.05093587

In [88]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# 행렬 만들기

In [89]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
data[0,1]

2

In [91]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [92]:
data[0:2, 0]

array([1, 3])

In [93]:
data.max()

6

In [94]:
data.min()

1

In [95]:
data.sum()

21

In [96]:
data = np.array([[1,2], [5,3], [4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [97]:
data.max(axis=0)

array([5, 6])

In [98]:
data.max(axis=1)

array([2, 5, 6])

In [99]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [100]:
# 크기가 다른 행렬 산술 연산의 경우
# 둘 중 한 행렬은 무조건 하나의 열 or 하나의 행만 있는 경우에만 가능하다.
# 이 경우 넘파이에서 브로드캐스트 규칙을 사용함.
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [101]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [102]:
np.ones(3)

array([1., 1., 1.])

In [103]:
np.zeros(3)

array([0., 0., 0.])

In [104]:
rng = np.random.default_rng()
rng.random(3)

array([0.7700884 , 0.69429042, 0.20481596])

In [105]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [106]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [107]:
rng.random((3,2))

array([[0.023966  , 0.4777323 ],
       [0.24490282, 0.69137591],
       [0.47081611, 0.44656327]])

# 난수 생성

In [108]:
rng.integers(5, size=(2,4))

array([[0, 2, 4, 1],
       [0, 1, 2, 4]], dtype=int64)

# get unique itmes and counts

In [110]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [111]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]
