# The Basic

- ndarray.ndim\
: 배열의 축(차원) 수
- ndarray.shape\
: 배열의 차원. n행 m열 = (n, m)
- ndarray.size\
: 배열의 총 요소 수.\
: 요소의 곱과 같다.
- ndarray.dtype\
: 배열의 요소 유형
- ndarray.itemsize\
: 배열의 각 요소 크기(바이트)
- ndarray.data\
: 배열의 실제 요소를 포함하는 버퍼

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int32'

In [5]:
a.itemsize

4

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [12]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

## Array 생성

In [1]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [2]:
a.dtype

dtype('int32')

In [3]:
b = np.array([1.2,3.5, 5.1])
b.dtype

dtype('float64')

In [4]:
a = np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [5]:
a = np.array([1,2,3,4])

In [6]:
# 시퀀스가 n개 들어가면 알아서 n차원 배열로 변환한다.
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
# 배열 유형을 생성할 때 명시적으로 저장할 수 있다.
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

- 영행렬

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- 1로 구성된 행렬

In [9]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

- 무작위 행렬

In [10]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

- array를 반환하는 arange
- np.arange(start, end, step)

In [11]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [12]:
# float도 가능
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [13]:
from numpy import pi
np.linspace(0, 2, 9) # 0 부터 2까지 9개의 숫자

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

In [15]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [16]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

## Printing Arrays

In [17]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [18]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [21]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [23]:
# 이거 돌리면 생략 안 되고 다 돌아감
# 근데 돌리면 진짜 답 없으니 주석처리 해놓음
# import sys
np.set_printoptions(threshold=sys.maxsize)

In [24]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


## Basic Operations

### elementwise

In [26]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [27]:
c = a - b
c

array([20, 29, 38, 47])

In [28]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [29]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [30]:
a < 35

array([ True,  True, False, False])

In [31]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [32]:
# 요소 별 연산 ( 행렬 연산 아님 )
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [33]:
# 행렬 곱
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [34]:
# @와 같은 행렬 곱
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [37]:
rg = np.random.default_rng(1)         # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3                                # 원래 1행렬인데 3이 곱해짐
a

array([[3, 3, 3],
       [3, 3, 3]])

In [39]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [40]:
# float로 이루어진 b행렬은 자동적으로 int로 변환되지 않아 에러가 난다.
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [41]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [42]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [43]:
c.dtype.name

'float64'

In [44]:
# j는 복소수임을 기억하자.
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [45]:
d.dtype.name

'complex128'

- 모든 요소의 합계를 계산하는 클래스 ndarray

In [46]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [47]:
a.sum()

3.1057109529998157

In [48]:
a.min()

0.027559113243068367

In [49]:
a.max()

0.8277025938204418

- 그러나 위 작업들은 행과 열을 따로 지정 안 한 것.
- 이때 axis 파라미터(매개변수)를 지정하면 원하는 대로 수행 가능

In [50]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
b.sum(axis=0) # column 별로 sum을 해준다.

array([12, 15, 18, 21])

In [52]:
b.min(axis=1) # row 별로 min을 구해준다.

array([0, 4, 8])

In [53]:
# cumsum : 누적합
b.cumsum(axis=1)   # row 별로 누적합을 구해줌.

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## Universal Functions (ufunc)
- 배열에서 요소별로 작동하는 함수
- 배열을 출력함

In [54]:
B = np.arange(3)
B

array([0, 1, 2])

In [55]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [56]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [57]:
# 요소별로 합해줌
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

## Indexing, Slicing, and Iterating

In [58]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [59]:
a[2]

8

In [61]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [63]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [64]:
# reversed a
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [65]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [66]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [67]:
b[2,3]

23

In [68]:
# 각 행에서 두번째 열
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [69]:
# 2번째 열
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [70]:
# 2,3번째 행
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

- 축 수보다 적은 수의 인덱스가 제공된 경우 누락된 인덱스는 완전한 조각으로 간주된다.

In [71]:
# b[-1, :]와 같다고 본다....
b[-1]

array([40, 41, 42, 43])

## dots(...)

In [72]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [73]:
c[1, ...]         # c[1, :, :] == c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [74]:
c[..., 2]         # c[:,:,-2]

array([[  2,  13],
       [102, 113]])

In [75]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [77]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape Manipulation
## Changing the shape of an array

In [78]:
a = np.floor(10 * rg.random((3,4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [79]:
a.shape

(3, 4)

In [80]:
# 배열은 납작하게 만들어줌 1차원으로
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [81]:
a.ravel().shape

(12,)

In [82]:
a.reshape(6,2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [83]:
# 전치행렬
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [84]:
a.T.shape

(4, 3)

In [86]:
# 근본적으로 a는 바뀌지 않음
a.shape

(3, 4)

- 함수 reshape는 수정된 모양으로 인수를 반환
- ndarray.resize 메서드는 배열 자체를 수정합니다.

In [87]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [88]:
a.resize((2,6))         # 배열 원본을 수정
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

- 나머지 차원 굳이 입력 안 하고 해결하기
- 마이너스 기호(-) 붙여버리기

In [89]:
a.reshape(3, -1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [90]:
a.reshape(3, -4)  # 음수기만 하면 다 된다.

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

## Stacking together different arrays

In [91]:
a = np.floor(10 * rg.random((2,2)))
a

array([[9., 7.],
       [5., 2.]])

In [92]:
b = np.floor(10 * rg.random((2,2)))
b

array([[1., 9.],
       [5., 1.]])

In [94]:
np.vstack((a, b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [95]:
np.hstack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

- column_stack은 1D 배열은 열로 2D로 쌓아준다.
- 2D에서의 hstack과 동일하다

In [97]:
from numpy import newaxis
np.column_stack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [98]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [99]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [100]:
a[:, newaxis]

array([[4.],
       [2.]])

In [101]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [102]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

- row_stack은 vstack과 동일하다

In [103]:
np.column_stack is np.hstack

False

In [104]:
np.row_stack is np.vstack

True