In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [5]:
print(a[0])

[1 2 3 4]


In [6]:
a[0]

array([1, 2, 3, 4])

In [7]:
a = np.array([1,2,3])

In [8]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.empty(2)

array([1., 1.])

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [15]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# 요소 추가, 제거 및 정렬

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

- argsort
- lexsort
- serarchsorted
- partition

In [19]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [20]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [22]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
x

array([[1, 2],
       [3, 4]])

In [24]:
y

array([[5, 6]])

In [25]:
(np.concatenate((x,y), axis=0)).shape

(3, 2)

# 배열의 모양과 크기
- ndarray.ndim : 배열의 축 또는 차원 수
- ndarray.size :  배열의 총 요소 수(=배열 모양 요소의 곱)
- ndarray.shape : 배열의 각 차원을 따라 저장된 요소 수를 나타내는 정수 튜플

In [26]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [27]:
# 배열의 차원 수
array_example.ndim

3

In [28]:
# 배열의 총 요소 수
array_example.size

24

In [29]:
# 배열의 모양
array_example.shape

(3, 2, 4)

# 배열 재구성

In [31]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [33]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

order 이거 잘 모르겠다 뭔 말이지

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

# 1D -> 2D

In [36]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [41]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [45]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [46]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [48]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [50]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [51]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# 인덱싱 및 슬라이싱

In [52]:
data = np.array([1,2,3])

data[1]

2

In [53]:
data[0:2]

array([1, 2])

In [54]:
data[1:]

array([2, 3])

In [55]:
data[-2:]

array([2, 3])

In [66]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [67]:
print(a[a < 5])

[1 2 3 4]


In [58]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [59]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [60]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [62]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [63]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [64]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [65]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [74]:
list(zip(b[0], b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [75]:
print(a[b])

[1 2 3 4]


In [77]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# 기존 데이터에서 배열 만들기

In [78]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [79]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [80]:
a1 = np.array([[1,1],
              [2,2]])
a2 = np.array([[3,3],
              [4,4]])

In [81]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [83]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [86]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [88]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

## 슬라이싱(얕은 복사)과 copy(깊은 복사)

In [89]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [90]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [91]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [92]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
b2 = a.copy()

In [95]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
b2[0, 0] = 1

In [98]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 기본 배열 작업

In [100]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [101]:
data - ones

array([0, 1])

In [102]:
data * data

array([1, 4])

In [103]:
data / data

array([1., 1.])

In [104]:
a = np.array([1,2,3,4])
a.sum()

10

In [105]:
b = np.array([[1,1], [2,2]])

In [106]:
b.sum(axis=0)

array([3, 3])

In [107]:
b

array([[1, 1],
       [2, 2]])

In [108]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

In [109]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

# More useful array operations

In [110]:
data.max()

2.0

In [111]:
data.min()

1.0

In [112]:
data.sum()

3.0