# Numpy python은 C를 기반으로 만들었다.
- C를 기반으로 만들었기 때문에 빠르다
- C의 데이터타입을 따른다.
- 강력하고 효율적이며, 쉽다.
- 자동적으로 모양을 맞춰준다.
---
* data
    - scalar 0차
    - vector 1차
    - metrics 2차
    - tensor 3차 이상
---
# 호모 시퀀스
- 인덱싱과 슬라이싱
---
# numpy 고유방식 5가지
- 콤마로 빠르게 접근 가능
- broadcasting
- fancy indexing (or advanced indexing)
- ... 이 있다.
- 인덱싱과 슬라이싱을 동시에 할 수 있다.

# 연산자에 대응하는 메소드가 있다.
---
# 메소드에 대응하는 함수가 있다.
---

# 연산자 오버로딩
원래 뒤에 붙이는 건데 같은 위치를 더하는 걸로

---
# 다형성
데이터 타입에 따라 연산 결과가 다르다
---

ㄷㄴ

* array

In [1]:
import array

In [2]:
[1,2,3] + [4,5,6] # element-wise

[1, 2, 3, 4, 5, 6]

In [3]:
[5,7,9]

[5, 7, 9]

* numpy

In [4]:
import numpy as np

In [29]:
a = np.array([1,2,3]) # factory method

In [6]:
# repr
a

array([1, 2, 3])

In [7]:
# repr
print(a)

[1 2 3]


In [12]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [8]:
b = np.array([1,'1', 2])

In [9]:
b

array(['1', '1', '2'], dtype='<U11')

* torch

In [10]:
import torch

ModuleNotFoundError: No module named 'torch'

In [11]:
x = torch.Tensor([1,2,4.1])

NameError: name 'torch' is not defined

In [ ]:
x

* tensorflow

In [13]:
import tensorflow as tf

In [26]:
a = tf.constant([1,2,3,4])

In [27]:
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [28]:
type(a)

tensorflow.python.framework.ops.EagerTensor

* numpy

In [16]:
import numpy as np

In [17]:
a = np.array([1,2,3])

In [18]:
a

array([1, 2, 3])

In [20]:
type(a)

numpy.ndarray

In [23]:
a.__class__

numpy.ndarray

In [25]:
# 쓰레기값 들어감 C언어 기반이라
np.ndarray((2,3))

array([[ 4.63939877e-308, -5.64938534e+036, -1.78409531e+046],
       [-4.32950182e-035, -8.72433218e-026, -1.57234264e-063]])

In [ ]:
a = np.array([1,2,3]) # factory method

In [32]:
aa = np.array([[1,2,3], [4,5,6]])

In [33]:
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
aa = np.array([[[1,2,3], [5,6,7]], [[1,2,3], [4,5,6]]])

In [49]:
aa

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [50]:
aa.shape

(2, 2, 3)

In [51]:
aa.dtype

dtype('int32')

In [53]:
aa.shape

(2, 2, 3)

In [54]:
aa.size

12

In [55]:
aa.ndim

3

In [57]:
np.zeros((4,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [68]:
np.ones([3,3,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [64]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.full((3,3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [61]:
np.triu([[1,2,3], [0, 2, 3], [0, 4, 5]])

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 5]])

In [63]:
np.lookfor('tri')

Search results for 'tri'
------------------------
numpy.tril
    Lower triangle of an array.
numpy.triu
    Upper triangle of an array.
numpy.matrix
    .. note:: It is no longer recommended to use this class, even for linear
numpy.asmatrix
    Interpret the input as a matrix.
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.sin
    Trigonometric sine, element-wise.
numpy.std
    Compute the standard deviation along the specified axis.
numpy.Str0
    A unicode string.
numpy.bmat
    Build a matrix object from a string, nested sequence, or array.
numpy.fromstring
    A new 1-D array initialized from text data in a string.
numpy.trim_zeros
    Trim the leading and/or trailing zeros from a 1-D array or sequence.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.hypot
    Given the "legs" of a right triangle, return its hypotenuse.
numpy.Bytes0
    A byte string.
numpy.MachAr
    Diagnosing machine parameters.
numpy.arc

In [65]:
help(np.tril)

Help on function tril in module numpy:

tril(m, k=0)
    Lower triangle of an array.
    
    Return a copy of an array with elements above the `k`-th diagonal zeroed.
    
    Parameters
    ----------
    m : array_like, shape (M, N)
        Input array.
    k : int, optional
        Diagonal above which to zero elements.  `k = 0` (the default) is the
        main diagonal, `k < 0` is below it and `k > 0` is above.
    
    Returns
    -------
    tril : ndarray, shape (M, N)
        Lower triangle of `m`, of same shape and data-type as `m`.
    
    See Also
    --------
    triu : same thing, only for the upper triangle
    
    Examples
    --------
    >>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 0,  0,  0],
           [ 4,  0,  0],
           [ 7,  8,  0],
           [10, 11, 12]])



In [69]:
a = np.arange(20).reshape(4,5)

In [70]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
a[1][0]

5

In [72]:
a[1,0]

5

In [73]:
a > 5 # broadcasting

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [74]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

* fancy indexing

In [76]:
# 차원 유지, 매트릭스로 뽑아옴. 벡터가 아니라.
a[[1,2]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
# 새로운 데이터 구조를 만든다.
a[[3,1,2]]

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
a[(0,1), (2,3)] # == a[[0,1], [2,3]]

array([2, 8])

In [80]:
a[[0,1], [2,3]]

array([2, 8])

In [82]:
# 인덱싱과 슬라이싱을 동시에 할 수 있다.
a[1, 2:5]

array([7, 8, 9])

In [83]:
a = np.arange(6).reshape(2,3)
b = np.arange(6, 12).reshape(2,3)

In [84]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [87]:
# + 연산자에 대응하는 __add__메소드가 있다
a.__add__(b)

array([[ 6,  8, 10],
       [12, 14, 16]])

In [88]:
# 메소드에 대응하는 함수가 있다.
np.add(a,b)

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# 연산자 오버로딩 overloading

In [89]:
[1,2] + [3,4,5,6]

[1, 2, 3, 4, 5, 6]

In [90]:
aa = np.arange(6).reshape(2,3)
bb = np.arange(6, 12).reshape(3,2)

In [91]:
aa + bb

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [92]:
# 모양을 맞추어준다 연산이 가능하도록
# broadcasting해준다.
aa + 1

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
# broadcasting
a > 3

array([[False, False, False],
       [False,  True,  True]])

In [95]:
aa * bb

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [96]:
# 행렬곱
aa @ bb

array([[ 28,  31],
       [100, 112]])

In [97]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [98]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [100]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## 1차

In [101]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [102]:
a*b

array([1, 4, 9])

In [103]:
# 내적
a.dot(b)

14

In [104]:
# 내적
np.dot(a,b)

14

In [115]:
# 내적
a @ b

14

In [105]:
np.multiply(a,b)

array([1, 4, 9])

## 2차

In [106]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [107]:
bb

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [109]:
np.multiply(aa, bb)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [110]:
# 다형성
np.dot(aa, bb)

array([[ 28,  31],
       [100, 112]])

In [112]:
# 다형성
aa.dot(bb)

array([[ 28,  31],
       [100, 112]])

In [113]:
aa @ bb

array([[ 28,  31],
       [100, 112]])

In [114]:
a @ b

14

In [120]:
aa = np.mat([[1,2,3],[3,4,5]])
bb = np.mat([[1,2,],[3,4,],[4,5]])

In [121]:
aa @ bb

matrix([[19, 25],
        [35, 47]])

In [122]:
aa * bb

matrix([[19, 25],
        [35, 47]])

In [123]:
np.multiply(aa, bb)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
ufunc