Creation\
\*: keyword only\
container: 한개로 묶어\
코어션\
vectorizer\
element\
numpy는 특정값을 어케 빨리 가져올까\
# axis
0: 행마다\
1: 열마다
# __iter__가 있으면 for를 돌릴 수 있다.
# flatiter : 차원축소
flatiter있으믄 next있음\
next로 돌림
# flaten은 copy, lavel은 view
# share하기 싫으면 copy
# numpy copy = deep copy가 default

In [4]:
import tensorflow as tf

In [3]:
a = tf.keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 3s 0us/step


In [4]:
(X_train, y_train), (X_test, y_test) = a

In [5]:
...

Ellipsis

In [6]:
X_train.shape

(60000, 28, 28)

In [7]:
X_train.dtype # dtype/8하면 item size가 나온다

dtype('uint8')

In [9]:
X_train.ndim

3

In [10]:
X_train.size

47040000

In [23]:
X_train.itemsize

1

In [3]:
import numpy as np

In [25]:
def x(a):
    return a.append('x')

In [26]:
a = [3,4,5]

In [27]:
x(a)

In [28]:
a

[3, 4, 5, 'x']

In [29]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
x.__annotations__

{}

In [2]:
import math

In [32]:
math.pi

3.141592653589793

In [33]:
np.pi

3.141592653589793

In [34]:
math.pi == np.pi

True

In [35]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [36]:
np.linspace(1, 50, 10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [8]:
a = np.array([[1,2,3]])
b = np.array([1,2,3])

In [9]:
a

array([[1, 2, 3]])

In [10]:
a.shape

(1, 3)

In [11]:
b.shape

(3,)

In [12]:
a+b

array([[2, 4, 6]])

In [14]:
np.ogrid[1:10, 1:10]

[array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])]

In [15]:
x, y = np.ogrid[1:10, 1:10]

In [16]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [17]:
x, y = np.ogrid[1:10:5j, 1:10]

In [18]:
x

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [19]:
y

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
a = np.arange(24).reshape(6, 4)

In [22]:
# 1개의 item마다 4byte를 차지한다는 의미
a.itemsize

4

In [21]:
a.strides

(16, 4)

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a.shape

(6, 4)

## axis
0: 행마다\
1: 열마다

In [27]:
a.sum(1)

array([ 6, 22, 38, 54, 70, 86])

In [30]:
a.sum(axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [28]:
a.sum(axis=0)

array([60, 66, 72, 78])

In [31]:
a = np.arange(24).reshape(2,3,4)

In [32]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
a.shape

(2, 3, 4)

In [34]:
a.sum()

276

In [35]:
a.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [37]:
a.sum(1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [38]:
def asb(a, b):
    return a+b

In [39]:
asb([1,2,3], [3,4,5])

[1, 2, 3, 3, 4, 5]

In [40]:
@np.vectorize
def asb(a, b):
    return a+b

In [41]:
asb([1,2,3], [3,4,5])

array([4, 6, 8])

In [42]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [45]:
# for 돌리기 가능~
'__iter__' in dir(a)

True

In [46]:
for i in a:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [47]:
a = np.arange(24).reshape(4, 6)

In [48]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [49]:
for i in a:
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]


In [50]:
dir(a.flat)

['__array__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'base',
 'coords',
 'copy',
 'index']

In [53]:
b = a.flat

In [60]:
next(b)

6

In [61]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# share

In [62]:
a = [1,2,3]

In [63]:
b = a

In [64]:
b[0] = 100

In [65]:
a

[100, 2, 3]

# copy 1

In [66]:
a = [1,2,3]

In [67]:
b = a.copy() # 새롭게 메모리 상에 값 만듦
# 공간을 많이 차지함

In [68]:
b[0] = 100

In [69]:
a

[1, 2, 3]

# copy 2

In [70]:
a = [1,2,3]

In [71]:
b = a[:]

In [72]:
b[0] = 100

In [73]:
a

[1, 2, 3]

# shallow copy

In [84]:
a = [[1,2,3], [4,5,6]]

In [85]:
a

[[1, 2, 3], [4, 5, 6]]

In [86]:
b = a.copy() # [:]

In [87]:
b[0] = 100

In [88]:
a

[[1, 2, 3], [4, 5, 6]]

In [77]:
# 깊은 안까지는 copy가 안 된다.
b[0][0] = 100

In [78]:
a

[[100, 2, 3], [4, 5, 6]]

# deep copy

In [79]:
import copy

In [80]:
a = [[1,2,3], [4,5,6]]

In [81]:
b = copy.deepcopy(a)

In [82]:
b[0][0] = 100

In [83]:
a

[[1, 2, 3], [4, 5, 6]]

# numpy copy = deep copy가 default