In [1]:
from scipy.signal import correlate, convolve

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,])

In [4]:
b = np.array([1,0,1])

In [7]:
correlate(a,b)

array([1, 2, 4, 6, 8, 4, 5])

In [8]:
convolve(a,b)

array([1, 2, 4, 6, 8, 4, 5])

In [9]:
b = np.array([1,0,-1])

In [10]:
correlate(a,b)

array([-1, -2, -2, -2, -2,  4,  5])

In [11]:
convolve(a,b) # <- flip

array([ 1,  2,  2,  2,  2, -4, -5])